Add trials project files
lu-jim/trials-review pull request #1
Opened 2021-09-27 15:22 UTC by lu-jim

# First PR for this project
- Added files from the original trials project
- Created a new branch for this PR to be reviewed

2021-09-27 22:10 UTC, lu-jim commented
Hi @lu-jim,
:clap: Great job so far! :clap: 
##  :confetti_ball:  To Highlight :confetti_ball:

- GitHub flow is followed. :heavy_check_mark:
- Readme is professional and descriptive :heavy_check_mark:

There are some issues that you still need to work on to go to the next project but you are almost there!
## Required Changes :recycle:

- [ ] Please use a separate CSS file for the project to follow HTML/CSS best practices. 
- [ ] Linters are not passing
- [ ] It would be good to use semantic tags for the welcome section to follow HTML/CSS best practices.
- [ ] Consider having the nav section inside the header section of the project to follow HTML/CSS best practices.
- [ ] Please use the same type of quotes for your CSS attributes.
- [ ] Please use space-less equal signs per HTML/CSS best practices
- [ ] Kindly avoid leaving old code as comments to have a clean project.

Cheers and Happy coding! :clap::clap::clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---
_As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form._

2021-09-27 22:32 UTC, rukundoeric requested changes
Hi @lu-jim, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Summary and usage of templates  💯
  - Fair result 💯 

## Required Changes ♻️
  - [ ] When requiring changes, you should also add why you requiring that change so that the students understand why they have to implement your required change.
  - [ ] Try to use inline comments so that it is easy to understand where exactly the problem is. check the example under the review.
  - [ ] When reviewing, please use github review feature by clicking on `file changes`. and If you are requiring changes, make sure to select `Request changes` as your review status.
  ![scrnli_9_20_2021_6-50-40 PM](https://user-images.githubusercontent.com/45217364/134042230-aea1ed74-0c55-421f-9e29-5c0ba15cffcd.png)
   if you do so, your review summary should have something like this above it:
   ![scrnli_9_20_2021_6-07-30 PM](https://user-images.githubusercontent.com/45217364/134042562-b983e722-9cb7-48fb-a4d8-3c8d37729dd8.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-09-27 22:32 UTC, rukundoeric commented on index.html
> +    <a href="sample.html#sushi">Sushi</a> -->
> Example of inline comment
- [ ] <b>REQUIRED:</b> To make sure that your codebase is always clean, remember to remove commented-codes.

2021-09-28 14:32 UTC, karam084 reviewed
You should explain more about what needs to be changed, and it is preferable to use the two methods of suggestion rather than order.

2021-09-28 14:33 UTC, alexisuwimana requested changes

2021-09-28 14:33 UTC, alexisuwimana commented on index.html
> +  body {
good Job so far @lu-jim but there is some change that needs to be done 

you need to remove inline styles

2021-10-02 11:43 UTC, lu-jim commented
Hi @lu-jim,
:clap:  Great job so far! :clap:
## :confetti_ball: To Highlight :confetti_ball:

- GitHub flow is followed. :heavy_check_mark:
- Readme is professional and descriptive :heavy_check_mark:

There are some issues that you still need to work on to go to the next project but you are almost there!
## Required Changes :recycle:
- [ ] See the annotations below
 
Cheers and Happy coding! :clap::clap::clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

_As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form._

2021-10-02 11:51 UTC, lu-jim commented on index.html
> +    <style>
Please use a separate CSS file for the project to follow HTML/CSS best practices.

2021-10-02 11:51 UTC, lu-jim commented on index.html
> +    background-color: lightblue;
Please use a separate CSS file for the project to follow HTML/CSS best practices.

2021-10-02 11:51 UTC, lu-jim commented on index.html
> +    <div id="welcome-section">
It would be good to use semantic tags such as <section> for the welcome section to follow HTML/CSS best practices.

2021-10-02 11:51 UTC, lu-jim commented on index.html
> +    <a href="sample.html#sushi">Sushi</a> -->
Kindly avoid leaving old code as comments to have a clean project.

2021-10-02 11:51 UTC, lu-jim commented on index.html
> +      <div class ="project-tile">
Please use space-less equal signs per HTML/CSS best practices

2021-10-02 11:51 UTC, lu-jim commented on index.html
> +    <nav id="navbar">
Consider having the nav section inside a header section of the project as suggested in the HTML/CSS best practices.

2021-10-02 11:57 UTC, rukundoeric approved these changes
Hi @lu-jim,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-02 12:02 UTC, merged